services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  migrate:
      image: migrate/migrate
      container_name: migration_tool
      command: ["sleep", "infinity"]
      volumes:
        - ./migrations:/migrations
      environment:
        DB_URL: mysql://devusr:devpassword@tcp(db:3306)/devdb?tls=false
      depends_on:
        db:
          condition: service_healthy
      networks:
        - backend
volumes:
  mysql_data:

networks:
  backend:
    name: backend